[package]
name = "aleym-daemon"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = "https://github.com/zefr0x/aleym/tree/main/daemon"
repository = { workspace = true }

[lints]
workspace = true
